### ISSUE TITLE
possible feature: support for assoc array param in newContext

### ISSUE THREAD

**Issue by JohnAD** [fenekku/moustachu#10]
This is one of two features I'd be interested in adding to this library.

Starting with the following example:

```
import moustachu

var t = """
<html>
  <body>
    <h1>{{forum_title}}</h1>
    <ul>
    {{# messages}}
      <li>content: {{content}}, author: {{author}}</li>
    {{/ messages}}
    </ul>
  </body>
</html>
"""

var messages: seq[Context] = @[]
var m = newContext()
m["content"] = "blah1"
m["author"] = "Joe"
messages.add(m)

var c = newContext()
c["forum_title"] = "XYZ"
c["messages"] = messages
echo(render(t, c))
```

It would be nice newContext had another variant that accepted an array of tuples, such that you could do:

```
import moustachu

var t = """
<html>
  <body>
    <h1>{{forum_title}}</h1>
    <ul>
    {{# messages}}
      <li>content: {{content}}, author: {{author}}</li>
    {{/ messages}}
    </ul>
  </body>
</html>
"""

var messages: seq[Context] = @[]
messages.add(newContext({"content": "blah1", "author": "Joe"}))  # this is the change

var c = newContext()
c["forum_title"] = "XYZ"
c["messages"] = messages
echo(render(t, c))
```

If interested in this feature, I'll start a PR this week. We will want to add border case tests.

**Comment by JohnAD** [comment]
Additionally, I would add this to the documentation.

In fact, I recommend adding the much of the generic 'moustache' documentation to this documentation. That way new users are less likely to get lost. I'd be happy to do that as well.

**Comment by fenekku** [comment]
#12 merged. I am closing this.
