### ISSUE TITLE
bug: empty seq with last markup

### ISSUE THREAD

**Issue by JohnAD** [fenekku/moustachu#13]
If the last item (token?) in a template is for a sequence,

```mustache
{{# something}}
{{{.}}}
{{/ something}}
```

But that sequence is empty, then an "IndexError" is generated in **ignore**.

Both conditions have to be true for this to happen. For now, a workaround is simply adding a new empty token at the end. For example:

```mustache
{{# something}}
{{{.}}}
{{/ something}}
{{ empty_text }}
```

For reference, the error message (as seen from my PR branch):

```
moustachu.nim(203)       render
moustachu.nim(114)       render
moustachu.nim(55)        ignore
system.nim(2833)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

A fix is already in my PR. As soon as I finish up documentation, I'll request a review.

**Comment by fenekku** [comment]
#12 should fix this!

**Comment by fenekku** [comment]
#12 merged. I am closing this.
