### ISSUE TITLE
add option to disable HTML escaping

### ISSUE THREAD

**Issue by davidnorthetal** [fenekku/moustachu#9]
so it can be used for non-HTML things as well.

Thanks for consideration and great work!

**Comment by fenekku** [comment]
Hi David,

Would the triple curly braces work for what you had in mind? Right now, you can do:

```nim
let text = "{{{non-escaped}}}" 
var c = newContext()
c["non-escaped"] = "1 < 2 && blue is not red"
render(text, c)  # "1 < 2 && blue is not red"
```

hope this helps!
